### ISSUE TITLE
Forbidden error

### ISSUE THREAD

**Issue by dozzy100** [whizzzkid/instagram-proxy-api#28]
I am using  a local version of this API to test the system. Everything worked great, but today I started getting the following error:

  {"code":2,"desc":"Failed to fetch from Instagram.","info":"encountered: TypeError: Cannot read property 'user' of undefinedfetched:{\"message\": \"forbidden\", \"status\": \"fail\"}"}

How do I overcome this?

**Comment by owldesign** [comment]
It looks like instagram changed something :(  Unless you are logged in, it will throw forbidden error..dang...facebook

**Comment by dozzy100** [comment]
If you try using the url generated by the proxy to access Instagram data in a browser, it works, even when not logged in. Maybe it is an issue with the user-agent.

Example url:

https://www.instagram.com/graphql/query/?query_id=17888483320059182&variables={%22first%22%3A20%2C%22id%22%3A%221606740656%22}

(Got the url by doing a console.log inside function InstaProxy.fetchFromInstagram, line 156 in app.js)

**Comment by nobilik** [comment]
@owldesign Really? But why I still can see things in my browser? I'm not logged in. No, they remove query_id and add query_hash, but with correct hash it still returns almost no data...

**Comment by croofec** [comment]
pls take a look the announcement https://www.instagram.com/developer/

> To continuously improve Instagram users' privacy and security, we are accelerating the deprecation of Instagram API Platform, making the following changes effective immediately. We understand that this may affect your business or services, and we appreciate your support in keeping our platform secure. 
> 
> These capabilities will be disabled immediately (previously set for July 31, 2018 or December 11, 2018 deprecation). The following will be deprecated according to the timeline we shared previously:
> 
> Public Content - all remaining capabilities to read public media on a user's behalf on December 11, 2018
> Basic - to read a user’s own profile info and media in early 2020
> For your reference, information on the new Instagram Graph API.

**Comment by sebastienfi** [comment]
@nobilik Can you share your solution ?

**Comment by nobilik** [comment]
@sebastienfi maybe I wasn't clear enough. I haven't solution, but I can see graphql query in browser developer console even if I'm not logged in to Instagram

**Comment by owldesign** [comment]
Try another browser and run same query. I did notice if I just simply logout from Instagram the query will still work (maybe left over cookies).

**Comment by whizzzkid** [comment]
I am not sure what is instagram upto. They do not want people to use their own data on instagram for other purposes. This is just plain wrong and at this point I think we should stop using instagram. That being said, I have a feeling that something like this might work for now:

https://www.instagram.com/graphql/query/?query_hash=42323d64886122307be10013ad2dcc44&variables={"first":3,"id":"1606740656"}

But then FB/I is trying to be an ass and does not wants to give us our own data. This can go away quickly.

**Comment by PudgeTheFish** [comment]
Is there any way to query instagram without being logged in as a user? It looks like this method only works when I'm logged in, otherwise I get an HTTP error 403 "You don't have authorization to view this page.".

**Comment by croofec** [comment]
https://igpi.ga/whizzzkid/media/?count=3 works again now

**Comment by lourou** [comment]
Now that Zuckerberg’s audition is done, Instagram API talk to us again, yay!

**Comment by whizzzkid** [comment]
Well, TBH I had a hunch about this. The only reason I did not work on a workaround was this gut feeling that this would either change again or go back to what it was. I was waiting for the dust to settle on this.

It's good everything is back to the way it was (for now), but I am pretty sure, bigger changes are coming. Let's keep this open for a while.

**Comment by owldesign** [comment]
Yeah its done, I don't think it'll ever be the same. Plus I always knew this wasn't somethign to rely on and expected a change eventually...it was waty too open (even if public infomation).

**Comment by itsmikeferrari** [comment]
I'm going to be looking into other scrapers. There are quite a few listed on HN.
https://news.ycombinator.com/item?id=15694118

**Comment by itsmikeferrari** [comment]
I modified the script that Brian Holt wrote. Brian: https://codepen.io/btholt/

Script
https://codepen.io/itsmikeferrari/pen/QmXyEN

**Comment by hatsantos** [comment]
I'm facing the same problem... :(
Will Instagram let us access the that? Or the only way will be a scrapper?

**Comment by whizzzkid** [comment]
@itsmikeferrari this looks promising.

**Comment by hatsantos** [comment]
@itsmikeferrari  is it possible to request multiple pages using that script?

I working and making some tests, and already publish an nodejs app to heroku were you could get that object. But I'n not seeing were I can try to request the second, third, fourth, etc page of the same user.

**Comment by Zerquix18** [comment]
It seems to work for hashtags... https://www.instagram.com/explore/tags/lala/?__a=1

**Comment by whizzzkid** [comment]
At this point, I would not trust IG regarding anything. Considering archiving this project.

**Comment by naiz0** [comment]
This is sad, but i understand you.
Thanks for your great work.

**Comment by whizzzkid** [comment]
I don't see this going anywhere. Archiving this project, no further development should be expected.
